
import os

# Define constants using integer values to avoid ANY string escaping ambiguity
quote = b'"'
# 92 is backslash
backslash = bytes([92])

# Construct the literal strings that appear in the HLX source code
# We want to write: if c == "\""
# So we need the string: "\""
lit_quote = quote + backslash + quote + quote

# We want to write: if source[i] == "\\"
# So we need the string: "\\"
lit_backslash = quote + backslash + backslash + quote

with open('part1.hlxc', 'wb') as f:
    # 1. HEADER & UTILS
    f.write(b"// HLX SELF-HOSTED COMPILER (Phase 4.2: Flat Context)\n\n")
    f.write(b"fn is_digit(c) -> bool {\n")
    f.write(b"    let code = ord(c);\n")
    f.write(b"    return code >= 48 and code <= 57;\n")
    f.write(b"}\n\n")
    f.write(b"fn is_alpha(c) -> bool {\n")
    f.write(b"    let code = ord(c);\n")
    f.write(b"    if code >= 97 and code <= 122 { return true; }\n")
    f.write(b"    if code >= 65 and code <= 90 { return true; }\n")
    f.write(b"    if code == 95 { return true; }\n")
    f.write(b"    return false;\n")
    f.write(b"}\n\n")

    # 2. TOKENIZER
    f.write(b"fn tokenize(source) -> object {\n")
    f.write(b"    let tokens = [];\n")
    f.write(b"    let i = 0;\n")
    f.write(b"    let len = len(source);\n")
    f.write(b"    loop (i < len, 1000000) {\n")
    f.write(b"        let c = source[i];\n")
    f.write(b"        if c == \" \" or c == \"\n\" or c == \"\t\" or c == \"\r\" {\n")
    f.write(b"            i = i + 1;\n")
    f.write(b"        } else {\n")
    f.write(b"            if is_alpha(c) {\n")
    f.write(b"                let ident = \"\";\n")
    f.write(b"                loop (i < len and is_alpha(source[i]), 100) {\n")
    f.write(b"                    ident = ident + source[i];\n")
    f.write(b"                    i = i + 1;\n")
    f.write(b"                }\n")
    f.write(b"                let type = \"IDENT\";\n")
    f.write(b"                if ident == \"fn\" { type = \"KW_FN\"; }\n")
    f.write(b"                if ident == \"let\" { type = \"KW_LET\"; }\n")
    f.write(b"                if ident == \"return\" { type = \"KW_RETURN\"; }\n")
    f.write(b"                if ident == \"if\" { type = \"KW_IF\"; }\n")
    f.write(b"                if ident == \"else\" { type = \"KW_ELSE\"; }\n")
    f.write(b"                if ident == \"loop\" { type = \"KW_LOOP\"; }\n")
    f.write(b"                if ident == \"break\" { type = \"KW_BREAK\"; }\n")
    f.write(b"                if ident == \"continue\" { type = \"KW_CONT\"; }\n")
    f.write(b"                if ident == \"and\" { type = \"OP_AND\"; }\n")
    f.write(b"                if ident == \"or\" { type = \"OP_OR\"; }\n")
    f.write(b"                if ident == \"true\" { type = \"LIT_BOOL\"; }\n")
    f.write(b"                if ident == \"false\" { type = \"LIT_BOOL\"; }\n")
    f.write(b"                if ident == \"null\" { type = \"LIT_NULL\"; }\n")
    f.write(b"                tokens = append(tokens, {\"type\": type, \"val\": ident});\n")
    f.write(b"            } else {\n")
    f.write(b"                if is_digit(c) {\n")
    f.write(b"                    let num = \"\";\n")
    f.write(b"                    loop (i < len and is_digit(source[i]), 100) {\n")
    f.write(b"                        num = num + source[i];\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                    }\n")
    f.write(b"                    tokens = append(tokens, {\"type\": \"LIT_INT\", \"val\": num});\n")
    f.write(b"                } else {\n")
    
    # TRICKY STRING PARSING LOGIC constructed with variables
    f.write(b"                    if c == " + lit_quote + b" {\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                        let s = \"\";\n")
    f.write(b"                        loop (i < len and source[i] != " + lit_quote + b", 1000000) {\n")
    f.write(b"                            if source[i] == " + lit_backslash + b" and i + 1 < len and source[i+1] == " + lit_quote + b" {\n")
    f.write(b"                                s = s + " + lit_quote + b";\n")
    f.write(b"                                i = i + 2;\n")
    f.write(b"                            } else {\n")
    f.write(b"                                s = s + source[i];\n")
    f.write(b"                                i = i + 1;\n")
    f.write(b"                            }\n")
    f.write(b"                        }\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                        tokens = append(tokens, {\"type\": \"LIT_STR\", \"val\": s});\n")
    f.write(b"                    } else {\n")
    
    # REST OF TOKENIZER (Symbols)
    f.write(b"                        let t = null;\n")
    f.write(b"                        if c == \"{\" { t = \"LBRACE\"; }\n")
    f.write(b"                        if c == \"}\" { t = \"RBRACE\"; }\n")
    f.write(b"                        if c == \"[\" { t = \"LBRACK\"; }\n")
    f.write(b"                        if c == \"]\" { t = \"RBRACK\"; }\n")
    f.write(b"                        if c == \"(\" { t = \"LPAREN\"; }\n")
    f.write(b"                        if c == \")\" { t = \"RPAREN\"; }\n")
    f.write(b"                        if c == \";\" { t = \"SEMI\"; }\n")
    f.write(b"                        if c == \":\" { t = \"COLON\"; }\n")
    f.write(b"                        if c == \",\" { t = \"COMMA\"; }\n")
    f.write(b"                        if c == \".\" { t = \"DOT\"; }\n")
    f.write(b"                        if c == \"+\" { t = \"OP_ADD\"; }\n")
    f.write(b"                        if c == \"-\" { t = \"OP_SUB\"; }\n")
    f.write(b"                        if c == \"*\" { t = \"OP_MUL\"; }\n")
    f.write(b"                        if t != null {\n")
    f.write(b"                            tokens = append(tokens, {\"type\": t, \"val\": c});\n")
    f.write(b"                            i = i + 1;\n")
    f.write(b"                        } else {\n")
    f.write(b"                            if c == \"=\" {\n")
    f.write(b"                                if i + 1 < len and source[i+1] == \"=\" {\n")
    f.write(b"                                    tokens = append(tokens, {\"type\": \"OP_EQ\", \"val\": \"==\"}); i = i + 2;\n")
    f.write(b"                                } else {\n")
    f.write(b"                                    tokens = append(tokens, {\"type\": \"OP_ASSIGN\", \"val\": \"=\"}); i = i + 1;\n")
    f.write(b"                                }\n")
    f.write(b"                            } else {\n")
    f.write(b"                                if c == \"!\" {\n")
    f.write(b"                                    if i + 1 < len and source[i+1] == \"=\" {\n")
    f.write(b"                                        tokens = append(tokens, {\"type\": \"OP_NE\", \"val\": \"!= \"}); i = i + 2;\n")
    f.write(b"                                    } else { i = i + 1; }\n")
    f.write(b"                                } else {\n")
    f.write(b"                                    if c == \"<\" {\n")
    f.write(b"                                        if i + 1 < len and source[i+1] == \"=\" {\n")
    f.write(b"                                            tokens = append(tokens, {\"type\": \"OP_LE\", \"val\": \"<=\"}); i = i + 2;\n")
    f.write(b"                                        } else {\n")
    f.write(b"                                            tokens = append(tokens, {\"type\": \"OP_LT\", \"val\": \"<\"}); i = i + 1;\n")
    f.write(b"                                        }\n")
    f.write(b"                                    } else {\n")
    f.write(b"                                        if c == \">\" {\n")
    f.write(b"                                            if i + 1 < len and source[i+1] == \"=\" {\n")
    f.write(b"                                                tokens = append(tokens, {\"type\": \"OP_GE\", \"val\": \">=\"}); i = i + 2;\n")
    f.write(b"                                            } else {\n")
    f.write(b"                                                tokens = append(tokens, {\"type\": \"OP_GT\", \"val\": \">\"}); i = i + 1;\n")
    f.write(b"                                            }\n")
    f.write(b"                                        } else {\n")
    f.write(b"                                            i = i + 1;\n")
    f.write(b"                                        }\n")
    f.write(b"                                    }\n")
    f.write(b"                                }\n")
    f.write(b"                            }\n")
    f.write(b"                        }\n")
    f.write(b"                    }\n")
    f.write(b"                }\n")
    f.write(b"            }\n")
    f.write(b"        }\n")
    f.write(b"    }\n")
    f.write(b"    return tokens;\n")
    f.write(b"}\n\n")

    # 3. PARSER (parse_primary)
    f.write(b"fn parse_primary(state) -> object {\n")
    f.write(b"    let i = state.pos;\n")
    f.write(b"    let t = state.tokens[i];\n")
    f.write(b"    if t.type == \"LIT_INT\" or t.type == \"LIT_STR\" or t.type == \"LIT_BOOL\" or t.type == \"LIT_NULL\" {\n")
    f.write(b"        state.node = {\"type\": \"Literal\", \"val\": t.val, \"lit_type\": t.type};\n")
    f.write(b"        state.pos = i + 1;\n")
    f.write(b"    } else {\n")
    f.write(b"        if t.type == \"LBRACK\" {\n")
    f.write(b"            state.pos = i + 1;\n")
    f.write(b"            let els = [];\n")
    f.write(b"            loop (state.tokens[state.pos].type != \"RBRACK\", 100000) {\n")
    f.write(b"                state = parse_expr(state);\n")
    f.write(b"                els = append(els, state.node);\n")
    f.write(b"                if state.tokens[state.pos].type == \"COMMA\" { state.pos = state.pos + 1; }\n")
    f.write(b"            }\n")
    f.write(b"            state.pos = state.pos + 1;\n")
    f.write(b"            state.node = {\"type\": \"Array\", \"elements\": els};\n")
    f.write(b"        } else {\n")
    f.write(b"            if t.type == \"LBRACE\" {\n")
    f.write(b"                state.pos = i + 1;\n")
    f.write(b"                let ks = []; let vs = [];\n")
    f.write(b"                loop (state.tokens[state.pos].type != \"RBRACE\", 100000) {\n")
    f.write(b"                    let key = state.tokens[state.pos].val;\n")
    f.write(b"                    state.pos = state.pos + 2;\n")
    f.write(b"                    state = parse_expr(state);\n")
    f.write(b"                    ks = append(ks, key); vs = append(vs, state.node);\n")
    f.write(b"                    if state.tokens[state.pos].type == \"COMMA\" { state.pos = state.pos + 1; }\n")
    f.write(b"                }\n")
    f.write(b"                state.pos = state.pos + 1;\n")
    f.write(b"                state.node = {\"type\": \"Object\", \"keys\": ks, \"values\": vs};\n")
    f.write(b"            } else {\n")
    f.write(b"                if t.type == \"IDENT\" {\n")
    f.write(b"                    state.node = {\"type\": \"Ident\", \"name\": t.val};\n")
    f.write(b"                    state.pos = i + 1;\n")
    f.write(b"                    loop (state.pos < len(state.tokens), 100000) {\n")
    f.write(b"                        let n = state.tokens[state.pos];\n")
    f.write(b"                        if n.type == \"LPAREN\" {\n")
    f.write(b"                            let name = state.node.name; state.pos = state.pos + 1;\n")
    f.write(b"                            let args = [];\n")
    f.write(b"                            loop (state.tokens[state.pos].type != \"RPAREN\", 100000) {\n")
    f.write(b"                                state = parse_expr(state); args = append(args, state.node);\n")
    f.write(b"                                if state.tokens[state.pos].type == \"COMMA\" { state.pos = state.pos + 1; }\n")
    f.write(b"                            }\n")
    f.write(b"                            state.pos = state.pos + 1;\n")
    f.write(b"                            state.node = {\"type\": \"Call\", \"func\": name, \"args\": args};\n")
    f.write(b"                        } else {\n")
    f.write(b"                            if n.type == \"LBRACK\" {\n")
    f.write(b"                                let o = state.node; state.pos = state.pos + 1;\n")
    f.write(b"                                state = parse_expr(state); state.pos = state.pos + 1;\n")
    f.write(b"                                state.node = {\"type\": \"Index\", \"object\": o, \"index\": state.node};\n")
    f.write(b"                            } else {\n")
    f.write(b"                                if n.type == \"DOT\" {\n")
    f.write(b"                                    let o = state.node; state.pos = state.pos + 2;\n")
    f.write(b"                                    state.node = {\"type\": \"Field\", \"object\": o, \"field\": state.tokens[state.pos-1].val};\n")
    f.write(b"                                } else { break; }\n")
    f.write(b"                            }\n")
    f.write(b"                        }\n")
    f.write(b"                    }\n")
    f.write(b"                }\n")
    f.write(b"            }\n")
    f.write(b"        }\n")
    f.write(b"    }\n")
    f.write(b"    return state;\n")
    f.write(b"}\n\n")

    # 4. PARSER (parse_expr)
    f.write(b"fn parse_expr(state) -> object {\n")
    f.write(b"    state = parse_primary(state);\n")
    f.write(b"    let lhs = state.node;\n")
    f.write(b"    if state.pos < len(state.tokens) {\n")
    f.write(b"        let op = state.tokens[state.pos];\n")
    f.write(b"        let ot = null;\n")
    f.write(b"        if op.type == \"OP_ADD\" { ot = \"Add\"; }\n")
    f.write(b"        if op.type == \"OP_SUB\" { ot = \"Sub\"; }\n")
    f.write(b"        if op.type == \"OP_MUL\" { ot = \"Mul\"; }\n")
    f.write(b"        if op.type == \"OP_EQ\"  { ot = \"Eq\"; }\n")
    f.write(b"        if op.type == \"OP_NE\"  { ot = \"Ne\"; }\n")
    f.write(b"        if op.type == \"OP_LT\"  { ot = \"Lt\"; }\n")
    f.write(b"        if op.type == \"OP_GT\"  { ot = \"Gt\"; }\n")
    f.write(b"        if op.type == \"OP_LE\"  { ot = \"Le\"; }\n")
    f.write(b"        if op.type == \"OP_GE\"  { ot = \"Ge\"; }\n")
    f.write(b"        if op.type == \"OP_AND\" { ot = \"And\"; }\n")
    f.write(b"        if op.type == \"OP_OR\"  { ot = \"Or\"; }\n")
    f.write(b"        if op.type == \"OP_ASSIGN\" { ot = \"Assign\"; }\n")
    f.write(b"        if ot != null {\n")
    f.write(b"            state.pos = state.pos + 1;\n")
    f.write(b"            state = parse_expr(state);\n")
    f.write(b"            state.node = {\"type\": \"BinOp\", \"op\": ot, \"lhs\": lhs, \"rhs\": state.node};\n")
    f.write(b"        }\n")
    f.write(b"    }\n")
    f.write(b"    return state;\n")
    f.write(b"}\n\n")

    # 5. PARSER (parse_stmt with ELSE)
    f.write(b"fn parse_stmt(state) -> object {\n")
    f.write(b"    let t = state.tokens[state.pos];\n")
    f.write(b"    if t.type == \"KW_LET\" {\n")
    f.write(b"        let name = state.tokens[state.pos+1].val; state.pos = state.pos + 3;\n")
    f.write(b"        state = parse_expr(state);\n")
    f.write(b"        state.node = {\"type\": \"Let\", \"name\": name, \"value\": state.node};\n")
    f.write(b"        state.pos = state.pos + 1;\n")
    f.write(b"    } else {\n")
    f.write(b"        if t.type == \"KW_RETURN\" {\n")
    f.write(b"            state.pos = state.pos + 1;\n")
    f.write(b"            state = parse_expr(state);\n")
    f.write(b"            state.node = {\"type\": \"Return\", \"value\": state.node};\n")
    f.write(b"            state.pos = state.pos + 1;\n")
    f.write(b"        } else {\n")
    f.write(b"            if t.type == \"KW_IF\" {\n")
    f.write(b"                state.pos = state.pos + 1; state = parse_expr(state);\n")
    f.write(b"                let cond = state.node; state.pos = state.pos + 1;\n")
    f.write(b"                let then = [];\n")
    f.write(b"                loop (state.tokens[state.pos].type != \"RBRACE\", 100000) {\n")
    f.write(b"                    state = parse_stmt(state); then = append(then, state.node);\n")
    f.write(b"                }\n")
    f.write(b"                state.pos = state.pos + 1;\n")
    f.write(b"                let els = [];\n")
    f.write(b"                if state.pos < len(state.tokens) {\n")
    f.write(b"                    if state.tokens[state.pos].type == \"KW_ELSE\" {\n")
    f.write(b"                        state.pos = state.pos + 2;\n")
    f.write(b"                        loop (state.tokens[state.pos].type != \"RBRACE\", 100000) {\n")
    f.write(b"                            state = parse_stmt(state); els = append(els, state.node);\n")
    f.write(b"                        }\n")
    f.write(b"                        state.pos = state.pos + 1;\n")
    f.write(b"                    }\n")
    f.write(b"                }\n")
    f.write(b"                state.node = {\"type\": \"If\", \"cond\": cond, \"then\": then, \"else\": els};\n")
    f.write(b"            } else {\n")
    f.write(b"                if t.type == \"KW_LOOP\" {\n")
    f.write(b"                    state.pos = state.pos + 2; state = parse_expr(state);\n")
    f.write(b"                    let cond = state.node; state.pos = state.pos + 1;\n")
    f.write(b"                    let mx = state.tokens[state.pos].val; state.pos = state.pos + 3;\n")
    f.write(b"                    let bdy = [];\n")
    f.write(b"                    loop (state.tokens[state.pos].type != \"RBRACE\", 100000) {\n")
    f.write(b"                        state = parse_stmt(state); bdy = append(bdy, state.node);\n")
    f.write(b"                    }\n")
    f.write(b"                    state.pos = state.pos + 1;\n")
    f.write(b"                    state.node = {\"type\": \"Loop\", \"cond\": cond, \"body\": bdy, \"max\": mx};\n")
    f.write(b"                } else {\n")
    f.write(b"                    if t.type == \"KW_BREAK\" {\n")
    f.write(b"                        state.node = {\"type\": \"Break\"};\n")
    f.write(b"                        state.pos = state.pos + 2; // break ;\n")
    f.write(b"                    } else {\n")
    f.write(b"                        if t.type == \"KW_CONT\" {\n")
    f.write(b"                            state.node = {\"type\": \"Continue\"};\n")
    f.write(b"                            state.pos = state.pos + 2; // continue ;\n")
    f.write(b"                        } else {\n")
    f.write(b"                            state = parse_expr(state);\n")
    f.write(b"                            let n = state.node;\n")
    f.write(b"                            if n.type == \"BinOp\" {\n")
    f.write(b"                                if n.op == \"Assign\" {\n")
    f.write(b"                                    state.node = {\"type\": \"Assign\", \"lhs\": n.lhs, \"rhs\": n.rhs};\n")
    f.write(b"                                }\n")
    f.write(b"                            }\n")
    f.write(b"                            state.pos = state.pos + 1;\n")
    f.write(b"                        }\n")
    f.write(b"                    }\n")
    f.write(b"                }\n")
    f.write(b"            }\n")
    f.write(b"        }\n")
    f.write(b"    }\n")
    f.write(b"    return state;\n")
    f.write(b"}\n")

print("Generated generate_part1_safe.py")
