quote = b'"'
backslash = b'\\'
lit_quote = quote + backslash + quote + quote
lit_backslash = quote + backslash + backslash + quote

with open('part1_debug.hlxc', 'wb') as f:
    f.write(b"// HLX SELF-HOSTED COMPILER (DEBUG)\n\n")
    f.write(b"fn is_digit(c) -> bool {\n")
    f.write(b"    let code = ord(c);\n")
    f.write(b"    return code >= 48 and code <= 57;\n")
    f.write(b"}\n\n")
    f.write(b"fn is_alpha(c) -> bool {\n")
    f.write(b"    let code = ord(c);\n")
    f.write(b"    if code >= 97 and code <= 122 { return true; }\n")
    f.write(b"    if code >= 65 and code <= 90 { return true; }\n")
    f.write(b"    if code == 95 { return true; }\n")
    f.write(b"    return false;\n")
    f.write(b"}\n\n")
    f.write(b"fn tokenize(source) -> object {\n")
    f.write(b"    let tokens = [];\n")
    f.write(b"    let i = 0;\n")
    f.write(b"    let len = len(source);\n")
    f.write(b"    loop (i < len, 1000000) {\n")
    f.write(b"        let c = source[i];\n")
    f.write(b"        if c == \" \" or c == \"\n\" or c == \"\t\" or c == \"\r\" {\n")
    f.write(b"            i = i + 1;\n")
    f.write(b"        } else {\n")
    f.write(b"            if is_alpha(c) {\n")
    f.write(b"                let ident = \"\";\n")
    f.write(b"                loop (i < len and is_alpha(source[i]), 100) {\n")
    f.write(b"                    ident = ident + source[i];\n")
    f.write(b"                    i = i + 1;\n")
    f.write(b"                }\n")
    f.write(b"                let type = \"IDENT\";\n")
    f.write(b"                if ident == \"fn\" { type = \"KW_FN\"; }\n")
    f.write(b"                if ident == \"let\" { type = \"KW_LET\"; }\n")
    f.write(b"                if ident == \"return\" { type = \"KW_RETURN\"; }\n")
    f.write(b"                if ident == \"if\" { type = \"KW_IF\"; }\n")
    f.write(b"                if ident == \"else\" { type = \"KW_ELSE\"; }\n")
    f.write(b"                if ident == \"loop\" { type = \"KW_LOOP\"; }\n")
    f.write(b"                if ident == \"break\" { type = \"KW_BREAK\"; }\n")
    f.write(b"                if ident == \"continue\" { type = \"KW_CONT\"; }\n")
    f.write(b"                if ident == \"and\" { type = \"OP_AND\"; }\n")
    f.write(b"                if ident == \"or\" { type = \"OP_OR\"; }\n")
    f.write(b"                if ident == \"true\" { type = \"LIT_BOOL\"; }\n")
    f.write(b"                if ident == \"false\" { type = \"LIT_BOOL\"; }\n")
    f.write(b"                if ident == \"null\" { type = \"LIT_NULL\"; }\n")
    f.write(b"                tokens = append(tokens, {\"type\": type, \"val\": ident});\n")
    f.write(b"            } else {\n")
    f.write(b"                if is_digit(c) {\n")
    f.write(b"                    let num = \"\";\n")
    f.write(b"                    loop (i < len and is_digit(source[i]), 100) {\n")
    f.write(b"                        num = num + source[i];\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                    }\n")
    f.write(b"                    tokens = append(tokens, {\"type\": \"LIT_INT\", \"val\": num});\n")
    f.write(b"                } else {\n")
    f.write(b"                    if c == " + lit_quote + b" {\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                        let s = \"\";\n")
    f.write(b"                        loop (i < len and source[i] != " + lit_quote + b", 1000000) {\n")
    f.write(b"                            if source[i] == " + lit_backslash + b" and i + 1 < len and source[i+1] == " + lit_quote + b" {\n")
    f.write(b"                                s = s + " + lit_quote + b";\n")
    f.write(b"                                i = i + 2;\n")
    f.write(b"                            } else {\n")
    f.write(b"                                s = s + source[i];\n")
    f.write(b"                                i = i + 1;\n")
    f.write(b"                            }\n")
    f.write(b"                        }\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                        tokens = append(tokens, {\"type\": \"LIT_STR\", \"val\": s});\n")
    f.write(b"                    } else {\n")
    f.write(b"                        // DUMMY REST\n")
    f.write(b"                        i = i + 1;\n")
    f.write(b"                    }\n")
    f.write(b"                }\n")
    f.write(b"            }\n")
    f.write(b"        }\n")
    f.write(b"    }\n")
    f.write(b"    return tokens;\n")
    f.write(b"}\n\n")
    f.write(b"fn parse_primary(state) -> object {\n")
    f.write(b"    return state;\n")
    f.write(b"}\n")

print("Generated part1_debug.hlxc line-by-line")
